### PR TITLE
Update to 2.0.0 release

### PR DESCRIPTION
**Pull request by hobu**
I have also added myself as a maintainer. @xhochy Please merge this after it goes ✅

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@hobu Nearly works, seems though like the rust output folder is named differently now.

**Comment by hobu** [comment]
I'm just flailing here trying to figure out how to get the `whitebox_tools` target installed. When I build locally, it is made, but when the recipe is built, it isn't in the same spot. Is there some conda forge setting that's building or putting stuff in different directories, and is there a command that's the equivalent of `make install`?

**Comment by hobu** [comment]
@xhochy Please merge this, I think we're ready to go!

**Comment by hobu** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
Need to use cargo-bundle-licenses to package the licenses of rust dependencies.
See https://github.com/conda-forge/vegafusion-python-embed-feedstock/blob/0a070c61bbc9ab0385cdb265f626d32fdec62b7a/recipe/meta.yaml#L18
https://github.com/conda-forge/vegafusion-python-embed-feedstock/blob/0a070c61bbc9ab0385cdb265f626d32fdec62b7a/recipe/meta.yaml#L26,
and https://github.com/conda-forge/vegafusion-python-embed-feedstock/blob/0a070c61bbc9ab0385cdb265f626d32fdec62b7a/recipe/meta.yaml#L46

**Comment by hobu** [comment]
I don't know much about rust packaging, but hopefully this covers what is required.

**Comment by hobu** [comment]
@isuruf license update applied. Please review/merge when you have a moment.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
